### ISSUE TITLE
Writing issue - age associations

### ISSUE THREAD

**Issue by rkboyce** [dbmi-pitt/EvidenceType-Calculator#17]
Comment: "It is noted by the authors that participants’ level of experience and subjective did impact the results of intra-rater reliability. However, the authors didn’t show any quantitative relationship between participants’ experience (e.g. number of years) and level of agreement. Whether the disagreement would decrease after controlling by years of experience was not presented in this paper. "

**Comment by rkboyce** [comment]
Discussion - we can't redo the analysis to account for years experience

Action - mention as a limitation

**Comment by epaulard7** [comment]
This issue is addressed in limitations.
